apiVersion: batch/v1
kind: Job
metadata:
  name: db-import
  namespace: family-tree
spec:
  template:
    spec:
      containers:
      - name: db-import
        image: mysql:8.0
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for MySQL to be ready..."
          until mysql -h mysql-service -u familytreeuser -pPassword123 familytreedb -e "SELECT 1" > /dev/null 2>&1; do
            echo "MySQL not ready yet, waiting..."
            sleep 5
          done
          echo "MySQL is ready! Importing database..."
          
          # Import the SQL file from the ConfigMap
          mysql -h mysql-service -u familytreeuser -pPassword123 familytreedb < /tmp/familytreedb.sql
          echo "✅ Database import completed successfully!"
          
          # Verification
          echo "📊 Database import verification:"
          mysql -h mysql-service -u familytreeuser -pPassword123 familytreedb -e "SHOW TABLES;"
          mysql -h mysql-service -u familytreeuser -pPassword123 familytreedb -e "SELECT COUNT(*) as table_count FROM information_schema.tables WHERE table_schema = 'familytreedb';"
        env:
        - name: MYSQL_PWD
          value: "Password123"
        volumeMounts:
        - name: sql-config
          mountPath: /tmp/familytreedb.sql
          subPath: familytreedb.sql
      volumes:
      - name: sql-config
        configMap:
          name: db-sql-config
      restartPolicy: Never
  backoffLimit: 2
