apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: family-tree
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo "Waiting for MySQL..."; sleep 5; done; echo "MySQL is ready!"']
      - name: fix-permissions
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            echo "Fixing file permissions..."
            chown -R 82:82 /var/www/storage /var/www/bootstrap/cache
            chmod -R 775 /var/www/storage /var/www/bootstrap/cache
            echo "✅ Permissions fixed"
        volumeMounts:
        - name: shared-storage
          mountPath: /var/www/storage
        - name: shared-storage
          mountPath: /var/www/bootstrap/cache
      containers:
      - name: laravel-app
        image: olakitanakinya/family-tree:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-storage
          mountPath: /var/www/storage
        - name: shared-storage
          mountPath: /var/www/bootstrap/cache
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "familytreedb"
        - name: DB_USERNAME
          value: "familytreeuser"
        - name: DB_PASSWORD
          value: "Password123"
        - name: APP_URL
          value: "http://98.81.89.67:30008"
        - name: ASSET_URL
          value: "http://98.81.89.67:30008"
        - name: APP_ENV
          value: "production"
        - name: APP_KEY
          value: "base64:9jvjThP6JJA5ENjR2evQ27g3H7YE0OtCG+szdOeUsvM="
        - name: APP_DEBUG
          value: "false"
        - name: FILESYSTEM_DISK
          value: "public"
        - name: SESSION_DRIVER
          value: "file"
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Final permission fix and start
            chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
            php artisan storage:link --force
            /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health.php
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: laravel-shared-storage
