apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: family-tree
  labels:
    app: laravel-app
spec:
  type: NodePort
  selector:
    app: laravel-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
