apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-shared-storage
  namespace: family-tree
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
