apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: family-tree
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: laravel-app
