apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-fix-config
  namespace: family-tree
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /var/www/public;
        index index.php index.html;

        # Fix for /public/ prefix in URLs - redirect to correct paths
        location ~* ^/public/(assets|storage)/(.*)$ {
            return 301 /$1/$2;
        }

        # Static assets
        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            try_files $uri $uri/ =404;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location ~ /\.ht {
            deny all;
        }
    }
